language: haskell

ghc:
    - "8.0"
env:
    - PACKAGEDIR="project"

before_install: cd ${PACKAGEDIR}

install:
    - cabal install --enable-tests

script:
    - cabal configure --enable-tests && cabal build && cabal test --show-details
